# Generated by Django 5.0.4 on 2024-04-24 14:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('occupied_percent', models.IntegerField()),
                ('battery_percent', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
