# Generated by Django 5.0.4 on 2024-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='battery_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='occupied_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
