# Generated by Django 5.0.4 on 2024-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_waste_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
